"""Polynomial LPA-prime solver for the scalar Ising Wetterich fixed point.

The potential is expanded about its running minimum kappa,

    u(rho) = sum_{n=2}^N lambda_n (rho-kappa)^n / n!

with rho = phi^2 / 2.  The optimized (Litim) regulator is used.  This is a
compact, auditable implementation intended to expose truncation convergence;
it is not a replacement for a full field-dependent O(partial^4) calculation.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from functools import cache
from math import gamma, pi

import numpy as np
import sympy as sp
from scipy.optimize import least_squares


@dataclass(frozen=True)
class LPASolution:
    dimension: float
    order: int
    kappa: float
    lambdas: tuple[float, ...]
    eta: float
    nu: float
    residual_norm: float
    relevant_eigenvalue: float

    def to_dict(self) -> dict[str, float | int | list[float]]:
        result = asdict(self)
        result["lambdas"] = list(self.lambdas)
        return result


def _loop_coefficient(dimension: float, eta: float) -> float:
    prefactor = (4.0 * pi) ** (-dimension / 2.0) / gamma(dimension / 2.0)
    return prefactor * ((2.0 - eta) / dimension + eta / (dimension + 2.0))


def anomalous_dimension(dimension: float, kappa: float, lambda_2: float) -> float:
    """LPA-prime anomalous dimension at the running potential minimum."""
    prefactor = 1.0 / (
        2.0 ** (dimension - 2.0)
        * pi ** (dimension / 2.0)
        * gamma(1.0 + dimension / 2.0)
    )
    denominator = (1.0 + 2.0 * kappa * lambda_2) ** 2
    return prefactor * kappa * lambda_2**2 / denominator


@cache
def _symbolic_beta_function(order: int, dimension: float):
    """Return a NumPy-callable beta function generated by symbolic differentiation."""
    rho = sp.symbols("rho", real=True)
    kappa = sp.symbols("kappa", positive=True)
    couplings = sp.symbols(f"l2:{order + 1}", real=True)
    dimension_symbol = sp.Float(dimension, 30)

    potential = sp.Integer(0)
    for n, coupling in enumerate(couplings, start=2):
        potential += coupling * (rho - kappa) ** n / sp.factorial(n)

    lambda_2 = couplings[0]
    eta_prefactor = 1 / (
        2 ** (dimension_symbol - 2)
        * sp.pi ** (dimension_symbol / 2)
        * sp.gamma(1 + dimension_symbol / 2)
    )
    eta = eta_prefactor * kappa * lambda_2**2 / (1 + 2 * kappa * lambda_2) ** 2
    loop = (4 * sp.pi) ** (-dimension_symbol / 2) / sp.gamma(dimension_symbol / 2)
    loop *= (2 - eta) / dimension_symbol + eta / (dimension_symbol + 2)

    u1 = sp.diff(potential, rho)
    u2 = sp.diff(potential, rho, 2)
    flow = (
        -dimension_symbol * potential
        + (dimension_symbol - 2 + eta) * rho * u1
        + loop / (1 + u1 + 2 * rho * u2)
    )

    flow_at_minimum = [
        sp.diff(flow, rho, n).subs(rho, kappa) for n in range(1, order + 1)
    ]
    kappa_flow = -flow_at_minimum[0] / lambda_2
    beta = [kappa_flow]
    for n in range(2, order + 1):
        beta_n = flow_at_minimum[n - 1]
        if n < order:
            beta_n += couplings[n - 1] * kappa_flow
        beta.append(beta_n)

    return sp.lambdify((kappa, *couplings), beta, modules="numpy")


def beta_vector(values: np.ndarray, dimension: float, order: int) -> np.ndarray:
    function = _symbolic_beta_function(order, float(dimension))
    with np.errstate(all="ignore"):
        result = np.asarray(function(*values), dtype=float)
    if result.shape != (order,) or not np.all(np.isfinite(result)):
        return np.full(order, 1e20)
    return result


def _jacobian(values: np.ndarray, dimension: float, order: int) -> np.ndarray:
    scale = np.maximum(1.0, np.abs(values))
    jacobian = np.empty((order, order), dtype=float)
    for column in range(order):
        step = 2e-6 * scale[column]
        plus = values.copy()
        minus = values.copy()
        plus[column] += step
        minus[column] -= step
        jacobian[:, column] = (
            beta_vector(plus, dimension, order) - beta_vector(minus, dimension, order)
        ) / (2.0 * step)
    return jacobian


def _candidate_guesses(
    order: int, previous: LPASolution | None, initial_guess: np.ndarray | None
) -> list[np.ndarray]:
    guesses: list[np.ndarray] = []
    if initial_guess is not None:
        guesses.append(np.asarray(initial_guess, dtype=float))
    if previous is not None:
        base = np.array([previous.kappa, *previous.lambdas], dtype=float)
        next_scale = max(10.0, 10.0 * abs(base[-1]))
        guesses.extend(
            [
                np.append(base, 0.0),
                np.append(base, 1.0),
                np.append(base, -1.0),
                np.append(base, 10.0),
                np.append(base, -10.0),
                np.append(base, next_scale),
                np.append(base, -next_scale),
            ]
        )
    if order == 2:
        for kappa in (0.015, 0.025, 0.035, 0.05, 0.08):
            for lambda_2 in (2.0, 5.0, 8.0, 12.0, 20.0):
                guesses.append(np.array([kappa, lambda_2]))
    return [guess for guess in guesses if guess.shape == (order,)]


def solve_fixed_point(
    dimension: float,
    order: int,
    previous: LPASolution | None = None,
    initial_guess: np.ndarray | None = None,
) -> LPASolution:
    """Solve the polynomial fixed-point equations and extract nu."""
    best = None
    for guess in _candidate_guesses(order, previous, initial_guess):
        def scaled_beta(values):
            return beta_vector(values, dimension, order) / (1.0 + np.abs(values))

        result = least_squares(
            scaled_beta,
            guess,
            xtol=1e-13,
            ftol=1e-13,
            gtol=1e-13,
            max_nfev=20_000,
            x_scale="jac",
        )
        residual = float(np.linalg.norm(result.fun))
        values = result.x
        if (
            result.success
            and residual < 1e-8
            and values[0] > 0
            and values[1] > 0
            and (best is None or residual < best[0])
        ):
            best = (residual, values)
    if best is None:
        raise RuntimeError(f"No physical fixed point found for D={dimension}, order={order}")

    residual, values = best
    stability = _jacobian(values, dimension, order)
    eigenvalues = np.linalg.eigvals(stability)
    real_eigenvalues = np.real(eigenvalues[np.abs(np.imag(eigenvalues)) < 1e-5])
    negative = real_eigenvalues[real_eigenvalues < -1e-6]
    if len(negative) == 0:
        raise RuntimeError("No relevant eigenvalue found in stability matrix")
    relevant = float(np.min(negative))
    nu = -1.0 / relevant
    eta = anomalous_dimension(dimension, values[0], values[1])
    return LPASolution(
        dimension=float(dimension),
        order=order,
        kappa=float(values[0]),
        lambdas=tuple(float(value) for value in values[1:]),
        eta=float(eta),
        nu=float(nu),
        residual_norm=residual,
        relevant_eigenvalue=relevant,
    )


def convergence_sequence(
    dimension: float = 3.0, minimum_order: int = 2, maximum_order: int = 7
) -> list[LPASolution]:
    solutions: list[LPASolution] = []
    previous = None
    for order in range(minimum_order, maximum_order + 1):
        solution = solve_fixed_point(dimension, order, previous=previous)
        solutions.append(solution)
        previous = solution
    return solutions
